### PR TITLE
Update classes/Kohana/ORM.php

### PR DESCRIPTION
**Pull request by neo22s**
Better to count using the primary key instead of *.

### CODE REVIEW

**Comment by zombor** [comment]
This needs a ticket number in the commit message, and it needs to be targeted to the develop branch.

**Comment by zombor** [comment]
Please read the CONTRIBUTING file in the main kohana/kohana repo for specific details.

**Comment by neo22s** [comment]
Hello,

I will read your CONTRIBUTING file I understand you have a process, just I saw the change and I want it to collaborate.

I will do it another day since I don't have time for it now.....

regards

**Comment by zeelot** [comment]
Sorry I didn't have time to respond to your pulls properly last night… It might be a good idea to quote the column name as well since `DB::expr()` will be skipping that. You can do so by calling `$this->_db->quote_column($this->_primary_key)` and you won't need to use the quotes around the column name (they get added).

Thanks for the help :)

**Comment by neo22s** [comment]
Sorry I am so new into this of github and collaborating in such project.

I created the issue in the tracking http://dev.kohanaframework.org/issues/4652

Thanks for your help :D I hope I get a bit more of time and help the project more, we have other improvements since we use KO in 3 different sites with thousands of visitors, it's time to get involved!

**Comment by hardlick** [comment]
thanks!

**Comment by neo22s** [comment]
so is it fixed? regards

**Comment by rjd22** [comment]
@neo22s Could you change the line in the pull request to the following like @Zeelot asked?: 
`->select(array(DB::expr('COUNT('.$this->_db->quote_column($this->_primary_key).')'), 'records_found'))`

Then we can merge your pull request.

**Comment by neo22s** [comment]
done, was about time! ;)

**Comment by zeelot** [comment]
It doesn't look like you made the change @rjd22  mentioned? Also, could you reopen a Pull Request for the `3.3/develop` branch instead of `3.3/master`?

**Comment by neo22s** [comment]
this is getting way more complicated than it is. Come on guys is just changing a line! I had this functions overrided in my apps since more than 2 years. I opened the bug also in the issue http://dev.kohanaframework.org/issues/4652

https://github.com/kohana/orm/pull/83

**Comment by neo22s** [comment]
You can close now this pull since I opened another one in the devel branch.

**Comment by zeelot** [comment]
I understand that it's a single line, but the master branches we have are for released versions of Kohana. We simply cannot edit master branches unless it's to create a new release. That's why @zombor said it needed to be moved to a develop branch (7 months ago, as soon as you submitted this change).

Thanks for taking the time to make the needed changes and get this into the next Kohana release.

**Comment by neo22s** [comment]
No problem, important that is fixed. I just see that there's not much proactivity . I also build OSS with KO and things are different. Thanks.

**Comment by rjd22** [comment]
@neo22s The most of other devs are really busy with other things. That is why we need the help from you guys. ;)

**Comment by neo22s** [comment]
I am aware of that. I have same situation. Take care.

**Pull request closed without merging**
