### PR TITLE
3.1.x

### PR DESCRIPTION
**Pull request by pocesar**
Just minor modification in the phpDoc on the validate exception class

### CODE REVIEW

**Comment by zombor** [comment]
Make sure you link to this in the phpdoc ticket in redmine.

**Comment by pocesar** [comment]
done :)

**Comment by pocesar** [comment]
added proper phpDoc for the orm class on the 3.1.x branch and modification proposal for the has() and remove() methods

**Comment by isaiahdw** [comment]
Can you please include a commit without all the coding style changes? I'd like you merge in your ORM phpDoc updates, but the coding style changes don't follow the Kohana convention so I can't merge them.

**Comment by pocesar** [comment]
well, I think I have it in my local repository, I use the 'format' function on netbeans to properly make spaces > tabs, and ends up modifying the braces as well. what are the Kohana conventions, so I can abide to them, because I intend to do a lot of pull requests as I go modifying modules and core files for phpDoc and fixes

**Comment by isaiahdw** [comment]
You can find the conventions here: http://kohanaframework.org/guide/about.conventions

When you do the phpDoc commits make sure they don't include any other changes. If you want other things changed do them in a different commit (and open issues for them) so we can decide what we want to do.

Thanks!

**Comment by pocesar** [comment]
ah ok, thanks. I commited the version with both modification and phpDoc, I will have to strip those off to another submodule and recommit only the phpDoc

**Pull request closed without merging**
