### PR TITLE
Allow custom User primary key when logging in

### PR DESCRIPTION
**Pull request by mvdnes**
change $user->id to $user->pk()

### CODE REVIEW

**Comment by kiall** [comment]
I'm not sure this makes sense - the auth schema includes a FK linking user_tokens.user_id to users.id ..

Can you explain what exactly is not working, I'm betting there is another fix for the issue.

**Comment by mvdnes** [comment]
My Auth_User begins like this

class Model_Lid extends Model_Auth_User {
        protected $_primary_key = 'persoon_id';
        protected $_table_name = 'leden';
        protected $_has_many = array(
            'user_tokens' => array(
                'model' =>  'user_token'
            ),

so saving fails as there is no id column

**Comment by kiall** [comment]
Humm - I'm not sure how well auth handles changing its schema around.. It obviously seems to be working for you with this change though!

Can you open a ticket on the [tracker](http://dev.kohanaframework.org/projects/kohana3/issues) and we'll get this merged when we cut a 3.3 branch ..

(Its possible this could be a BC break if there is any possibility of changing `_primary_key` and leaving this code intact.. if that is not possible, we can probably merge into 3.1/3.2)

**Comment by mvdnes** [comment]
See http://dev.kohanaframework.org/issues/4222
And this is indeed the only thing needed to get a custom primary key working.

**Pull request closed without merging**
