### PR TITLE
Update ORM.php

### PR DESCRIPTION
**Pull request by aqlx86**
i think this force_login() method should return something

### CODE REVIEW

**Comment by Sebjugate** [comment]
Agreed. I came to the exact same conclusion.

**Comment by zeelot** [comment]
Can't merge PRs into master branches, you should file a ticket and get this done in `3.4/develop` (probably not a minor release).

**Comment by tommcdo** [comment]
I feel like this should actually go into all releases. It's clearly a bug. The doc says `@return boolean`, and without a return value, there's no sensible way to detect whether `force_login()` was successful.

**Comment by zombor** [comment]
That's fine. The point is we don't merge bug fixes directly to master. We have a release process.

**Comment by tommcdo** [comment]
Agreed. I'm commenting on @Zeelot's suggestion to file a ticket against `3.4/develop` instead of against a minor release. If it were a feature request, then 3.4 would be an appropriate target, but this is a bug and should be fixed on all releases. It's documented to do something but it does not do it. (Compare to `Auth_File->force_login()`.)

**Pull request closed without merging**
