### PR TITLE
Refs #4497: ORM::values() second param isn't optional anymore

### PR DESCRIPTION
**Pull request by kemo**
http://dev.kohanaframework.org/issues/4497

### CODE REVIEW

**Comment by zeelot** [comment]
I agree with this change but please make a clean PR with the proper change as the only commit. Feel free to reopen this if you fix the branch or go ahead and make a new branch with new PR.

**Comment by kemo** [comment]
If you just merged 3.3 only the single commit would be in the PR, nvm I'll send another one

**Comment by zeelot** [comment]
Ah, let me do that! One second.

**Comment by zeelot** [comment]
Hmm… still a weird PR… not sure why composer.json is showing up when it's already in `3.4/develop`

**Comment by kemo** [comment]
Haha, just merge #95 :)

**Comment by zeelot** [comment]
so close!

**Pull request closed without merging**
